biology = {
    'respiration': [
        ["What are the products of aerobic respiration?", "carbon dioxide and water"],
        ["What are the products of anaerobic respiration in yeast?", "ethanol and carbon dioxide"],
        ["What are the products of anaerobic respiration in humans?", "lactic acid"],
        ["What happens during inhalation?", "external intercostal muscles contract\ninternal intercostal muscles relax\nribs and sternum move up and out\ndiaphragm contracts and flattens\nchest cavity volume increases\npressure decreases\nair rushes in"],
        ["What happens during exhalation?", "external intercostal muscles relax\ninternal intercostal muscles contract\nribs and sternum return to original position\ndiaphagm relaxes and arches\nchest cavity volume decreases\npressure increases\nair rushes out"],
        ["What is the composition of nitrogen in inhaled and exhaled air?", "78% and 78%"],
        ["What is the composition of oxygen in inhaled and exhaled air?", "20% and 16%"],
        ["What is the composition of carbon dioxide in inhaled and exhaled air?", "0.03% and 4%"],
        ["What is the composition of water vapour in inhaled and exhaled air?", "variable and saturated"],
        ["What is the composition of dust in inhaled and exhaled air?", "variable and little"],
        ["What is the temperature of inhaled and exhaled air?", "variable and body temperature"],
        ["What adaptations does the nose have?", "hair, mucus, sensory cells"],
        ["What adaptations do the alveoli have?", "large surface area to volume ratio, one-cell thick walls, thin film of moisture, network of blood capillaries"],
        ["What harmful effects does nicotine have on the body?", "addictive\ncauses the release of adrenaline\nmakes blood clot easily"],
        ["What harmful effects does carbon monoxide have on the body?", "binds irreversibly with haemoglobin to form carboxyhaemoglobin\nincreases the rate of fatty deposits on inner arterial wall -> coronary heart disease"],
        ["What harmful effects does tar have on the body?", "causes uncontrolled cell division -> cancer\nparalyses cilia lining the air passages -> chronic bronchitis and emphysema"],
        ["What harmful effects do irritants have on the body?", "paralyses cilia lining the air passages -> chronic bronchitis and emphysema"],
        ["What happens when a person has chronic bronchitis?", "prolonged exposure to irritant particles\nepithelium of air passages becomes inflamed\nexcessive mucus secreted by epithelium\ncilia become paralysed\nmucus and dust particles cannot be removed\nair passages become blocked\npersistent coughing to clear air passages"],
        ["What happens when a person has emphysema?", "persistent violent coughing due to bronchitis\npartition walls between aleveoli break down\ndecreased surface area to volume ratio for gaseous exchange\nlungs lose elasticity and become inflated with air\nwheezing and severe breathlessness"],
    ],
    'nutrition in man': [
        ["What chemicals are present in the mouth?", "amylase"],
        ["What chemicals are present in the stomach?", "hydrochloric acid, pepsinogen, prorennin"],
        ["What chemicals are present in pancreatic juice?", "lipase, amylase and trypsinogen"],
        ["What chemicals are present in intestinal juice?", "peptidases, lipase, enterokinase, dissacharide enzymes"],
        ["Where does carbohydrate digestion occur?", "mouth and small intestine"],
        ["Where does protein digestion occur?", "stomach and small intestine"],
        ["Where does fat digestion occur?", "small intestine"],
        ["What adaptations does the small intestine have?", "folds, villi, microvilli, one-cell thick epithelium, length"],
        ["What happens to glucose in the body?", "distributed for respiration for energy; excess is converted by liver and muscles to glycogen for storage"],
        ["What happens to amino acids in the body?", "synthesis of new protoplasm for growth and repair, synthesis of enzymes and hormones; excess is deaminated in the liver"],
        ["What happens to fats in the body?", "build protoplasm (cell membranes), broken down to provide energy; excess is stored in adipose tissue"],
        ["What are the functions of the liver?", "protein synthesis, deamination, iron storage, detoxification, bile, glucose regulation"]
    ],
    'nutrition in plants': [
        ["What is the equation for the light-dependent stage of photosynthesis?", "12 H2O -> 6 O2 + 24 H"],
        ["What is the equation for the light-independent stage of photosynthesis?", "6 CO2 + 24 H -> C6H12O6 + 6 H2O"],
        ["What is the overall equation for photosynthesis?", "6 CO2 + 12 H2O -> C6H12O6 + 6 O2 + 6 H2O"],
        ["What is the overall simplified equation for photosynthesis?", "6 CO2 + 6 H2O -> C6H12O6 + 6 O2"],
        ["Where does photolysis of water occur?", "grana"],
        ["Where does the reduction of carbon occur?", "stroma"],
        ["What happens to the stomata in the day?", "photosynthesis\nK+ ions are AT-ed from epidermal cells into GC\nWP becomes more negative\nwater moves in by osmosis\nGC becomes turgid, swollen\nthicker cell wall on one side causes swollen GC to become more curved\nstoma opens"],
        ["What happens to the stomata in the night?", "K+ ions diffuse out of the GC\nWP becomes less negative\nwater moves out by osmosis\nGC becomes flaccid\nstoma closes"]
    ],
    'inheritance': [
        ["Define gene.", "unit of inheritance"],
        ["Define gene locus.", "place on chromosome where gene is located"],
        ["Define allele.", "different forms of the same gene"],
        ["Define homologous chromosomes.", "chromosomes which have the same sequence of gene loci, same shape and same length"],
        ["Define dominant allele.", "only 1 copy of the allele is needed to express the phenotype"],
        ["Define recessive allele.", "2 copies of the allele are needed to express the phenotype"],
        ["Define codominant alleles.", "both traits are expressed"],
        ["List out the components needed in a genetic diagram.", "parents (phenotype, genotype, gametes), random fertilisation, offspring (genotype, phenotype), ratio"],
        ["What can cause a spontaneous mutation in DNA?", "radiation, mutagenic chemicals, viruses"]
    ],
    'homeostasis': [
        ["Define negative feedback", "set norm to be maintained\nreceptor that detects deviation from set norm\ncontrol center that receives nerve signal from receptor and stimulates effectors to initiate response\ncorrective mechanism that brings about reverse effect of stimulus\nfeedback to receptors that set point has been reached"],
        ["Define homeostasis", "maintenance of a constant internal environment"]
    ],
    'eye': [
        ["From outside in, what are the three layers of the eyeball?", "sclera, choroid and retina"],
        ["What is the function of the sclera?", "protect eyeball from mechanical damage"],
        ["What is the function of the choroid?", "prevent internal reflection of light and has blood vessels to transport nutrients and waste products"],
        ["What is the function of the retina?", "contains photoreceptors to detect light"],
        ["What is the function of the vitreous chamber?", "keep eyeball firm and refract light"],
        ["What is the function of the conjunctiva?", "secrete mucus to keep eyeball moist"],
        ["What is the function of the cornea?", "refract light"],
        ["What is the function of the aqueous chamber?", "keep front of eyeball firm and refract light"],
        ["What is the function of the ciliary body?", "control curvature and thickness of lens"],
        ["What is the function of the suspensory ligament?", "attach lens to ciliary body"],
        ["What is the function of the lens?", "changes shape and thickness to refract light"],
        ["What is the function of the rectus muscle?", "control movement of eyeball"],
        ["What is the function of the optic nerve?", "transmit nerve impulses from photoreceptors in retina to brain"],
        ["What is the function of the pupil?", "allow light to enter eye"],
        ["What is the function of the iris?", "control amount of light entering the eye"],
        ["What is the function of the eyelids?", "protect cornea from mechanical damage"],
        ["What is the function of the eyelashes", "shield the eye from dust particles"],
        ["What is the function of the tear gland?", "secrete tears to wash away dust particles, keep cornea moist and lubricate conjunctiva"],
        ["Where is light refracted?", "cornea, aqueous chamber, lens and vitreous chamber"],
        ["What happens to the iris in bright light?", "circular muscles contract\nradial muscles relax\npupil constricts"],
        ["What happens to the iris in dim light?", "circular muscles relax\nradical muscles contract\npupil dilates"],
        ["What happens to the lens when looking at a far object?", "light rays are parallel\nciliary muscles relax\nsuspensory ligament becomes taut\nlens become thinner"],
        ["What happens to the lens when looking at a near object?", "light rays are divergent\nciliary muscles contract\nsuspensory ligament becomes slack\nlens become rounder"]
    ],
    'reproduction in plants': [
        ["Explain the process of double fertilisation.", "pollen grain lands on stigma\nsugary fluid secreted by stigma causes germaination of pollen grain\nenzymes digest the tissue of the style, forming a pollen tube that extends towards the ovule\npollen tube nucleus directs growth of pollen tube\ngenerative nucleus divides to form 2 male gametes\npollen tube reaches micropyle, absorbs saps and bursts, releasing the 2 male gametes\n1 male gamete + ovum -> diploid zygote\n1 male gamete + 2 polar nuclei -> triploid endosperm nucleus"],
        ["What happens to the integuments post-fertilisation?", "seed coat"],
        ["Explain the process of tissue culture.", "remove the explant from the meristematic region of the plant\nsterilise the explant by washing it in dilute detergent and bleach\nplace explant in nutrient solution with auxin and place on shaker\ncallus pieces are formed and their cells are totipotent\ntransfer callus pieces into agar medium with cytokinin to induce shoot formation\ntransfer shoot to another agar medium with auxin to induce root formation\ntransfer to soil in a greenhouse with constant environmental conditions via greenhouse\ntransfer plants to field"]
    ]
}

geography = {
    'tourism': [
        ["What are the components of an investigation?", "hypothesis, collect data (equipment, procedure), analyse data, present data, conclusion"],
        ["What are the 3 different kinds of sampling?", "random, systematic, stratified"],
        ["What are the advantages of random sampling?", "unbiased, can be used with large sample populations"],
        ["What are the disadvantages of random sampling?", "leads to poor representation if large areas are not hit by the random number generator"],
        ["What are the advantages of systematic sampling?", "more straightforward, good coverage can be easily achieved"],
        ["What are the disadvantages of systematic sampling?", "more biased"],
        ["What are the advantages of stratified sampling?", "more representative of the whole population, saves time"],
        ["What are the disadvantages of stratified sampling?", "can only be used if sample pool can be divided into categories, may be hard to identify categories effectively"],
        ["Give an example of ecotourism.", "Waitomo Caves, New Zealand\nglowworms light up the caves\nNew Zealand government partners with local Maori people\nhuman impact is monitored and tour operation closes when carbon dioxide levels are too high\ncarrying capacity ensures that not too many people are in the caves\nvoted best practice in ecotourism"]
    ],
    'food resources': [
        ["What are the health impacts of inadequate food consumption?", "malnutrition, ill-health, starvation"],
        ["What are the economic impacts of inadequate food consumption?", "lower productivity, higher public health expenditures, long-term debt"],
        ["What are the political impacts of inadequate food consumption?", "social unrest"],
        ["What are the social impacts of inadequate food consumption?", "scavenging"],
        ["What are some statistics about malnutrition in the world?", "75% of people in the Democratic Republic of Congo suffer from malnutrition"],
        ["What is an example of ill-health due to inadequate food consumption?", "inadequate consumption of fruits and vegetables leads to vitamin A deficiency, which may cause visual impairment and blindness\nan estimated 250 000 to 500 000 children become blind every year in LDCs"],
        ["What are some statistics about starvation in the world?", "5 million people were threatened with starvation in Mali in 2012"],
        ["What is a case study of lower productivity due to inadequate food consumption?", "Sierra Leone, India, Sri Lanka and Ethiopia\nlow levels of nutrition intake were associated with lower levels of productivity\nfarmers are less innovative, less experimental or unable to implement improvements"],
        ["What is a case study of long-term debt due to inadequate food consumption?", "food supplied as aid is up to 34% more expensive than if purchased locally\nLDCs incurred losses amounting to US$5-7 billion"],
        ["What is a case study of social unrest due to inadequate food consumption?", "Mozambique\nfood prices increased by as much as 30%\ninitially peaceful protests turned violent\n10 dead, 400 injured"],
        ["What is a case study of scavenging due to inadequate food consumption?", "Smokey Mountain landfill in Manila\npoor families set up makeshift homes near the dump to have quick and easy access to waste"],
        ["What are the health impacts of excess food consumption?", "obesity and related illnesses"],
        ["What are the economic impacts of excess food consumption?", "lower productivity, higher public health expenditure"],
        ["What are the social impacts of excess food consumption?", "food wastage, dieting"],
        ["What is a case study of obesity and related illnesses due to excess food consumption?", "obesity rates in the USA rose from 14.5% in 1971 to 30.9% in 2000"],
        ["What are some statistics about lower productivity due to excess food consumption?", "people with BMI over 40 are twice as likely to fall sick or be injured while doing work"],
        ["What are some statistics about food wastage due to excess food consumption?", "each year, consumers in DCs waste 230 million tonnes of food\nwasted food per capita in DCs is 95-115kg compared to 6-11kg in LDCs"],
        ["What are some statistics about the dieting industry?", "weight loss industry in USA was valued at US$20 billion in 2012"],
        ["What is the increase in land used around the world for GM foods from 1996-2011?", "1.7 million hectares to 160 million hectares"],
        ["What are the benefits of GM foods?", "increased food supply\nincreased income for farmers\nreduced environmental pollution\nimproved nutritional value of food"],
        ["What are some crops that are GM foods?", "soya bean, corn, canola, rice"],
        ["What qualities do GM foods have?", "increased resistance to diseases\ngrow faster"],
        ["How do GM foods increase income for farmers?", "increased resistance to disease means less crops are damaged and output increases\nability to stay fresh for a longer time allows for export to countries further away and increases income earned"],
        ["How do GM foods increase food supply?", "increased yield\nfaster growth, more harvests per year\nincreased shelf life of crops"],
        ["What are the statistics for the unequal consumption of food in the world?", "average amount of food available is 2800 kcal per person, average amount of food needed is 2586 kcal per person\nrichest 20% consume 50% of meat and fish vs poorest 20% consume 5% of meat in the world"],
        ["What are the physical causes of food shortage?", "climate change, extreme weather events, pests"],
        ["What are the negative impacts of climate change on food supply?", "causes previously usable farmland to become suitable or farming\nshrinking of glaciers due to increased temperatures causes lack of water for irrigation" ],
        ["What are the positive impacts of climate change on food supply?", "may lengthen growing seasons for some regions\nmay allow for farming in areas previously unsuitable to farm in"], 
        ["What are some statistics on the impact of climate change on food supply?", "due to increasing temperatures food production in Canada, China, northern US etc increased by 35%\nIPCC: glaciers in Himalayas may melt entirely by 2025, dependent on by farmers in China and India for plant irrigation via glacial melt in major river"],
        ["How does extreme weather events cause food shortage?", "droughts, cold waves, heat waves and tropical cyclones abuse crop damage, make it difficult to grow crops, decreasing food production\nworsened in countries unable to recover from loss of crops"],
        ["What are some statistics on extreme weather events causing food shortage?", "Cyclone Yasi destroyed half of Queensland's crops\nstate is one of the world's top sugar cane  exporters\n1/3 of its crops in the way of cyclone\nresulting in in losses of $500 million"],
        ["What are some statistics on pests causing food shortages?", "Liberia was in a state of emergency in 2009 due to caterpillar infestation\naffected 46 villages\nworsened already serious food shortage problem"],
        ["What are the political causes to food shortage?", "civil strife, poor governance"],
        ["How does civil strife cause food shortage?", "when the country experiences major internal conflicts, it can lead to dispute over control of resources that affect food production\nlandmines could reduce or stop food production during or after conflict"],
        ["What are some statistics on ow civil strife causes food shortage?", "critical shortge of food, water and medical supplies in Houla, Syria\nfamilies who normally relied on farming and cattle ranching sold land to buy food\neconomic cycle disrupted"],
        ["How does poor governance cause food shortage?", "corruption, policy errors, inability to implement food policies can cause food shortage"],
        ["What are some statistics on poor governance causing food shortage?", "40,000 villagers in Madya Pradesh, India were deprived of farm land\nland used to develop mining, steel plant, ports\nvillagers lost means to produce food, left with extremely limited income to buy food"],
        ["What are economic factors that causes food shortage?", "food policy, increasing cost of fertiliser and transport, demand from emerging economies, converting farmland to industrial production"],
        ["How does food policy affect food supply?", "stockpiling helps ensure food stability during emergencies, but may cause old shortages in other countries\nfood subsidies, which is money paid bu governments or organisations to make food more affordable, help ensure that the poor can afford food"], 
        ["What are some statistics on how stockpiling affects food supply?", "Algeria bought 800,000 tones of wheat for stockpiling\ncaused Saudi Arabia to double stockpile, and Indonesia to buy 4x usual amount\ncaused decreased food supply worldwide, causing rices to increase, worsening food shortage in some LDCs"], 
        ["What are some statistics on food subsidies?", "the US government distributed US$74.6 billion worth of subsidies to 47.7 million Americans in Massachusetts in the form of food stamps given to people with low income\nSri Lanka gave discounted rations to half of population regardless of income before 1979, causing wealthy to benefit from rations while poor and needy still experiencing food shortage. After 1979, the distribution was changed to income based distribution, increasing calorie consumption by 12% among poorest 20%"], 
        ["How does the increase in cost of fertiliser and transport affect food supply?", "increase in cost of fertilisers, causes cost of food production to increase, increasing food price\nincrease in fuel cost, increase cost of transport and machine operation, increase cost of food production\nsince poor people already spend large proportion of income n food, increase in price means they may not ge enough food to meet nutritional needs"],
        ["What are some statistics for the increase of cost of fertiliser and transport?", "world crude oil prices increase by 10.3% in 2011, causing Kazakhstan, a major wheat producer, increased its price of exported wheat to neighbouring countries"],
        ["How does demand from emerging economies cause food shortage?", "Brazil, Russia, India and China (BRIC) have increased food demand, especially meat and fish demand\ndue to rapidly growing middle class with increased urhasing power and changing food preferences\ncaused depletion of global food inventories, especially grains\nmay result in food shortage in poorer countries"], 
        ["How does converting farmland to industrial production cause food shortage?", "cash crops are more profitable than food crops such as biofuels like corn,  sugar cane, and palm oil\nproduction of crash crops increase due to increased demand"], 
        ["What are some statistics on converting farmland to industrial production?", "according to the US department of agriculture in 2009, 25% of food crops grown in USA are fuels instead of food crops, which would have been able to feed 330 million people for a year"], 
        ["What are social factors of food shortage?", "lack of accessibility, lack of logistics of food distribution, rapid population growth"],
        ["How does lack of accessibility cause food shortage?", "how easily residents can reach food available is dependent on transport infrastructure like roads, rail links and number and location of food outlets available\nwhen links are unavailable or food outlets are few and far apart, people may not be able to obtain fresh produce, causing food shortage"], 
        ["How does the lack of logistics of food distribution cause food shortage?", "as food stability - the movement of food from farms to retail shops - depends on good transport network, which may be affected by physical barriers sh as mountains or events like landslides"], 
        ["What are some statistics on how the lack of logistics of food distribution affect food shortage?", "Timor Leste experiences food shortages between harvests, but are unable to receive logistical help in numerous remote parts of the country"],
        ["What are some statistics on rapid population growth affecting food supply?", "in Sub-Saharan Africa, 75% of Africans will have to rely on food aid by 2025\nalready small amount of farm land declining due to increasing temperatures\nworsened by high population growth in bth rural and urban areas"]
    ],
    'health and diseases': [
        ["What are the social factors causing the spread of malaria?", "poor drainage and stagnant water, improper sanitation, overcrowded living conditions"],
        ["What are the economic factors causing the spread of malaria?", "limited provision of and access to healthcare"],
        ["What are the environmental factors causing the spread of malaria?", "effect of climate"],
        ["What are the social impacts of malaria?", "death rate and infant mortality rate"],
        ["What are the economic impacts of malaria?", "cost of health care, loss of productivity and burden on households"],
        ["What are the social factors causing the spread of HIV/AIDS?", "social stigma, lack of education, lifestyle choices, lapses in medical practices"],
        ["What are the economic factors causing the spread of HIV/AIDS?", "vice trades and mobility"],
        ["What are the social impacts of HIV/AIDS?", "life expectancy, infant mortality rate and orphan crisis"],
        ["What are the economic impacts of HIV/AIDS?", "cost of health care, loss of productivity and slower economic growth"],
        ["What can individuals do to manage infectious diseases?", "exercise social responsibility\ntake preventive measures\nrefrain from risk-taking behaviours\nget vaccinated\nfollow travel advisories"],
        ["What can communities do to manage infectious diseases?", "community-based mosquito control in Nicaragua\n surveyed residents' understanding of dengue and mosquito-control practices, identified breedings sites\ndengue infection in children fell by 50%\nhouseholds were 25% less likely to have breeding sites\nneeded cooperation from government to deal with water and waste management issues"],
        ["What precautionary measures can governments implement to manage infectious diseases?", "thermal fogging in Thailand\ndistribute insecticides by using fog\nkills adult mosquitoes outdoors\nexpensive, must be done regularly, reduces visibility, traffic hazard"],
        ["What mitigation measures can governments implement to manage infectious diseases?", "vector control in Singapore\n'Do the Mozzie Wipeout' community outreach campaign to raise awareness on prevention methods\ncited by WHO has a good role model in preventing and managing dengue cases\nclimate change, new dominant virus Den-1"],
        ["What can international organisations do to manage infectious diseases?", "UNAIDS Getting to Zero\nbring together resources for coordinated and accountable efforts against AIDS\nsupported Kenya and reduced new HIV infections among children by 44%\nsocial stigma, discrimination"],
        ["What can non-governmental organisations do to manage infectious diseases?", "International HIV/AIDS Alliance\nadvocates for HIV, health and human rights, increases access to HIV health programmes and supporting other groups responding to HIV\nprovided nearly 1.5 million HIV treatment, care and support packages and reached nearly 380 000 people with programmes addressing stigma and discrimination in 2016"]
    ]
}

integrated_humanities = {
    'un': [
        ["What is the context to a successful peacekeeping mission?", "pressure to successfully bring peace back\nno vested interests among member states\nmission is on high priority\n\ncombat fatigue\nno incentive to prolong war\nno support from foreign power"],
        ["What is the context to an unsuccessful peacekeeping mission?", "vested interests of member countries\nmission is not on high priority\nUN involvement in other conflicts; resources stretched thin\n\nstrong incentive to prolong war\nexternal suport from foreign powers"],
        ["What are the main aims of UN peacekeeping missions?", "monitor and verify ceasefire\ndisarm, demobilise, reintegrate troops\nensure fair elections\ntackle humanitarian crisis"],
        ["Why is disarmament and demobilisation important to the peacekeeping mission?", "eliminates inclination for warring factions to return to using violent means"],
        ["Why is reintegration of troops important to the peacekeeping mission?", "provide new lives and purpose for rebels\npeople now share a common goal of rebuilding country"],
        ["Why is the trust between warring factions important to the peacekeeping mission?", "both parties trust that the other faction will also disarm\nthey need not fear being militarily disadvantaged"],
        ["Why are the correct incentives and disincentives important to the peacekeeping mission?", "warring factions know that it is illogical to continue fighting\nmore inclined to lay down arms for peace"],
        ["Why is humanitarian aid important to the peacekeeping mission?", "allows for transition into peacebuilding\nensures long-term stability"],
        ["How much manpower did ONUMOZ have?", "8300 troops"],
        ["What humanitarian aid did ONUMOZ provide Mozambique?", "poverty eradication\nencouraged all school-aged militants to go to school\nhelped 3.7 million people displaced by war resettle\nprotect human rights\nchange from violence-oriented mindset to pro-development"],
        ["How successful was DDR in Mozambique?", "76 000 soldiers disarmed and demobiliseds\n150 000 weapons collected"],
        ["How much manpower did UNAVEM II have?", "350 unarmed military observers"],
        ["How successful was DDR in Angola?", "delayed and incomplete\n37% of MPLA and 85% of UNITA troops demobilised by deadline\nonly 8 800 had joined the joint army"]
    ]
}

contents = {
    'bio': biology,
    'geog': geography,
    'ih': integrated_humanities
}